name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  android-test:
    name: Build & Test Android (ComposeApp)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # -----------------------------
      # TESTS
      # -----------------------------
      - name: Run tests
        run: ./gradlew :composeApp:test
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

      - name: Upload test reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: composeApp/build/reports/tests/
          if-no-files-found: ignore

      # -----------------------------
      # APK ANDROID
      # -----------------------------
      - name: Build debug APK
        run: ./gradlew :composeApp:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: composeApp/build/outputs/apk/debug/
          if-no-files-found: ignore